site_name: UniOS Docs

nav: 
 - Home: index.md
 - UniBackpack: unibackpack.md

theme: 
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  
  palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode

      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: purple
        accent: purple
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: purple
        accent: purple
        toggle:
          icon: material/brightness-4
          name: Switch to system preference`
